# ReScript is not yet compatible with Yarn2 PnP, so we need this.
# See https://github.com/rescript-lang/rescript-compiler/issues/3276
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.3.0.cjs
