// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var weatherData = [
  {
    id: 2650225,
    location: "Edinburgh, UK",
    icon: {
      code: "321",
      description: "shower drizzle"
    },
    temperature: {
      current: "9",
      minimum: "5.5",
      maximum: "11.0"
    },
    wind: {
      speed: "15.5",
      fromDegrees: 340
    }
  },
  {
    id: 2643741,
    location: "London, UK",
    icon: {
      code: "801",
      description: "few clouds"
    },
    temperature: {
      current: "16",
      minimum: "13.0",
      maximum: "20.0"
    },
    wind: {
      speed: "7.0",
      fromDegrees: 150
    }
  },
  {
    id: 2988507,
    location: "Paris, FR",
    icon: {
      code: "202",
      description: "thunderstorm with heavy rain"
    },
    temperature: {
      current: "12",
      minimum: "9.5",
      maximum: "14.0"
    },
    wind: {
      speed: "8.0",
      fromDegrees: 225
    }
  },
  {
    id: 1850147,
    location: "Tokyo, JP",
    icon: {
      code: "781",
      description: "tornado"
    },
    temperature: {
      current: "18",
      minimum: "12.0",
      maximum: "24.5"
    },
    wind: {
      speed: "4.0",
      fromDegrees: 200
    }
  },
  {
    id: 658225,
    location: "Helsinki, FI",
    icon: {
      code: "602",
      description: "heavy snow"
    },
    temperature: {
      current: "-10",
      minimum: "-15.0",
      maximum: "-6.0"
    },
    wind: {
      speed: "0.5",
      fromDegrees: 10
    }
  },
  {
    id: 4887398,
    location: "Chicago, US",
    icon: {
      code: "905",
      description: "windy"
    },
    temperature: {
      current: "15",
      minimum: "13.0",
      maximum: "18.0"
    },
    wind: {
      speed: "30.0",
      fromDegrees: 60
    }
  }
];

exports.weatherData = weatherData;
/* No side effect */
