// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MockData = require("./MockData.bs.js");

function fetchData(param) {
  return MockData.weatherData;
}

exports.fetchData = fetchData;
/* No side effect */
