// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function $$Location(Props) {
  var name = Props.name;
  return React.createElement("div", undefined, name);
}

var make = $$Location;

exports.make = make;
/* react Not a pure module */
