// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var MockData = require("../../services/MockData.bs.js");
var WeatherPanel = require("./weather-panel/WeatherPanel.bs.js");

import './WeatherWidget.css'
;

function WeatherWidget(Props) {
  return React.createElement("div", {
              className: "weather-widget"
            }, React.createElement(WeatherPanel.make, {
                  locations: MockData.weatherData,
                  currentIndex: 0
                }));
}

var make = WeatherWidget;

exports.make = make;
/*  Not a pure module */
