// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var $$Location = require("./components/Location.bs.js");
var Caml_array = require("rescript/lib/js/caml_array.js");

import '/src/styles/icons/owfont-regular.css'
;

function WeatherPanel(Props) {
  var locations = Props.locations;
  var currentIndex = Props.currentIndex;
  return React.createElement("div", {
              className: "weather-panel"
            }, React.createElement($$Location.make, {
                  name: Caml_array.get(locations, currentIndex).location
                }));
}

var make = WeatherPanel;

exports.make = make;
/*  Not a pure module */
