// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var WeatherWidget = require("./weather-widget/WeatherWidget.bs.js");

import './App.css'
;

function App(Props) {
  return React.createElement("div", {
              className: "app"
            }, React.createElement("div", {
                  className: "app-content"
                }, React.createElement(WeatherWidget.make, {})));
}

var make = App;

exports.make = make;
/*  Not a pure module */
