// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Hello = require("./Hello.bs.js");
var React = require("react");

function App(Props) {
  return React.createElement(Hello.make, {});
}

var make = App;

exports.make = make;
/* Hello Not a pure module */
