// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Hello(Props) {
  var name = Props.name;
  var greeting = "Hello " + (
    name !== undefined ? name : "stranger"
  ) + "!";
  return React.createElement("div", undefined, greeting);
}

var make = Hello;

exports.make = make;
/* react Not a pure module */
