// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var App = require("./components/App.bs.js");
var React = require("react");
var ReactDom = require("react-dom");

import './Main.css'
;

var root = document.querySelector("#root");

if (root == null) {
  console.log("No #root component found");
} else {
  ReactDom.render(React.createElement(React.StrictMode, {
            children: React.createElement(App.make, {})
          }), root);
}

/*  Not a pure module */
